### ISSUE TITLE
Error on startup: IsADirectoryError: [Errno 21] Is a directory: '/etc/hydraplay/hydra.config.json'

### ISSUE THREAD

**Issue by zwometer** [mariolukas/HydraPlay#42] opened 2021-11-19 17:42 UTC
I did a new install from scratch.
Cloned the project.
docker-compose build
then created and edited the hydraplay.private.json

additionally I had to edit one port int the docker-compose.yml because I already have a webserver running on port 8080, so I changed
    ports:
      - 8080:8080
to
    ports:
      - 8090:8080

when I start it with docker-compose up I get:

Attaching to hydraplay
hydraplay    | 2021-11-19 17:34:32,545 [9:140400629872448] DEBUG - hydraplay.config: Loading config file.
hydraplay    | Traceback (most recent call last):
hydraplay    |   File "/hydraplay/hydraplay.sh", line 14, in <module>
hydraplay    |     main()
hydraplay    |   File "/hydraplay/hydraplay.sh", line 11, in main
hydraplay    |     hydraplay.main.main()
hydraplay    |   File "/hydraplay/hydraplay/main.py", line 116, in main
hydraplay    |     server = HydraServer()
hydraplay    |   File "/hydraplay/hydraplay/server/HydraServer.py", line 26, in __init__
hydraplay    |     self.config = Config(self.base_path)
hydraplay    |   File "/hydraplay/hydraplay/config.py", line 10, in __init__
hydraplay    |     self.content = self.load_json(file_name)
hydraplay    |   File "/hydraplay/hydraplay/config.py", line 15, in load_json
hydraplay    |     with open(file) as json_data_file:
hydraplay    | IsADirectoryError: [Errno 21] Is a directory: '/etc/hydraplay/hydra.config.json'
hydraplay exited with code 1

**Comment by mariolukas** [comment] 2021-11-19 17:59
I am not able to reproduce this issue. Ist the mount point for the config in the compose file correct? It should be 

- ./hydra.private.json:/etc/hydraplay/hydra.config.json

Did you start from scratch or have you tried an early version, before today. In case of a previous build i would suggest to delete the old image and start with a fresh image build.

**Comment by zwometer** [comment] 2021-11-19 18:06
this is what the whole compose file looks like:

> version: "3.5"
services:
  hydraplay:
    privileged: true
    build:
      context: docker/
      dockerfile: Dockerfile
      args:
        SNAPCASTVERSION: 0.25.0
    container_name: hydraplay
    ports:
      - 8090:8080
      - 1780:1780
      - 1704:1704
      - 1705:1705
      - 6600-6679:6600-6679
      - 6680-6690:6680-6690
    volumes:
       - ./src/:/hydraplay
       - ./hydra.private.json:/etc/hydraplay/hydra.config.json
    #environment:
      #- DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_mopidy
>

I had it working earlier today (before your update).
to start from a clean slate I stopped it with `docker-compose down`, removed it with `docker rm hydraplay`, and deleted the whole directory with all the config jsons and the compose file.

**Comment by mariolukas** [comment] 2021-11-19 21:53
fixed within 64b929771cca758de2f96cc94c9ee7217999d347

**Closed** 2021-11-19 21:54 UTC
